name: CI (Guix)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  guix:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout project
        uses: actions/checkout@v6

      - name: Install Guix
        uses: PromyLOPh/guix-install-action@v1
        with:
          pullAfterInstall: false

      - name: Cache Guix Manifest NAR
        id: guix-cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/guix
            ~/guix-manifest-cache
          key: guix-manifest-${{ runner.os }}-${{ hashFiles('channels.scm', 'manifest.scm') }}

      - name: Restore Guix Manifest NAR
        if: steps.guix-cache.outputs.cache-hit == 'true'
        run: |
          set -xeuo pipefail

          sudo "$(which guix)" archive --authorize < ~/guix-manifest-cache/signing-key.pub
          guix archive --import < ~/guix-manifest-cache/manifest.nar

      - name: Build in Guix shell
        run: guix time-machine -C channels.scm -- shell -m manifest.scm -- cargo build

      - name: Lint in Guix shell
        run: guix time-machine -C channels.scm -- shell -m manifest.scm -- cargo clippy -- -D warnings

      - name: Test in Guix shell
        run: guix time-machine -C channels.scm -- shell -m manifest.scm -- cargo test

      - name: Save Guix Manifest NAR
        if: always() && steps.guix-cache.outputs.cache-hit != 'true'
        run: |
          set -xeuo pipefail

          mkdir -p ~/guix-manifest-cache
          guix time-machine -C channels.scm -- build -m manifest.scm \
            | xargs guix archive --export -r > ~/guix-manifest-cache/manifest.nar

          # signing key is generated by guix-install-action
          cp /etc/guix/signing-key.pub ~/guix-manifest-cache/signing-key.pub
